### ISSUE TITLE
Does not delete detector object

### ISSUE THREAD

**Issue by ashrantaryal** [paleckar/matlab-dlib-facetrack#1]
Hi,
I tried the code and it works as expected. The only problem is that it does not seem to delete the detector object when I call detector('delete', h);. When I run the code with multiple images, my memory gets full and MATLAB crashes. Do you have a possible solution for this? I am using MATLAB 2017a.

**Comment by paleckar** [comment]
Hi,
thanks for noticing this. The bug was in the `detector.cpp` file, more precisely in the destructor of the `Detector` class where I had forgotten to delete a reference to the shape predictor `_sp`.

I have recompiled with 2018b for both Windows 10 x64 and Ubuntu 16.04 and updated the repo. If you want, you can build the `.mexa64` file yourself, it's just something like

`mex -I/home/user/dlib-19.2 -L/home/user/dlib-19.2/examples/build/dlib_build -ldlib detector.cpp`

Hope it works now and please let me know if it works so I can close the issue.

**Comment by ashrantaryal** [comment]
Yes, that fixed the memory issue. Thank you for the very quick response.
